# This is a YAML-formatted file

image:
  repository: azurearcfork8s.azurecr.io
  releaseName: arc-preview
  imagePullPolicy: IfNotPresent

features:
  autoUpdate: false
  clusterConnect:
    enabled: true
  customLocations:
    enabled: false
  azureRbac:
    enabled: false
    appId: ""
    appSecret: ""
